/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/layouts/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Gatsby theme colors
        "color-text": "var(--color-text)",
        "color-text-2": "var(--color-text-2)",
        "color-text-3": "var(--color-text-3)",
        "color-white": "var(--color-white)",
        "color-nav-bar": "var(--color-nav-bar)",
        "color-nav-border": "var(--color-nav-border)",
        "color-category-button": "var(--color-category-button)",
        "color-background": "var(--color-background)",
        "color-button-background": "var(--color-button-background)",
        "color-button-text": "var(--color-button-text)",
        "color-post-background": "var(--color-post-background)",
        "color-card": "var(--color-card)",
        "color-code": "var(--color-code)",
        "color-code-block": "var(--color-code-block)",
        "color-gray-1": "var(--color-gray-1)",
        "color-gray-2": "var(--color-gray-2)",
        "color-gray-3": "var(--color-gray-3)",
        "color-gray-4": "var(--color-gray-4)",
        "color-gray-5": "var(--color-gray-5)",
        "color-gray-6": "var(--color-gray-6)",
        "color-divider": "var(--color-divider)",
        "color-blue": "var(--color-blue)",
        "color-blue-icon": "var(--color-blue-icon)",
        "color-icon-hover": "var(--color-icon-hover)",
        "color-icon": "var(--color-icon)",
      },
      fontSize: {
        "text-xs": "var(--text-xs)",
        "text-sm": "var(--text-sm)",
        "text-base": "var(--text-base)",
        "text-md": "var(--text-md)",
        "text-title": "var(--text-title)",
        "text-lg": "var(--text-lg)",
        "text-xl": "var(--text-xl)",
      },
      fontWeight: {
        "font-weight-regular": "var(--font-weight-regular)",
        "font-weight-medium": "var(--font-weight-medium)",
        "font-weight-semi-bold": "var(--font-weight-semi-bold)",
        "font-weight-bold": "var(--font-weight-bold)",
        "font-weight-extra-bold": "var(--font-weight-extra-bold)",
      },
      spacing: {
        "sizing-xs": "var(--sizing-xs)",
        "sizing-sm": "var(--sizing-sm)",
        "sizing-base": "var(--sizing-base)",
        "sizing-md": "var(--sizing-md)",
        "sizing-lg": "var(--sizing-lg)",
        "sizing-xl": "var(--sizing-xl)",
        "padding-sm": "var(--padding-sm)",
        "padding-lg": "var(--padding-lg)",
        "grid-gap-sm": "var(--grid-gap-sm)",
        "grid-gap-lg": "var(--grid-gap-lg)",
        "grid-gap-xl": "var(--grid-gap-xl)",
        "nav-height": "var(--nav-height)",
        "footer-height": "var(--footer-height)",
        "min-width": "var(--min-width)",
        width: "var(--width)",
        "post-width": "var(--post-width)",
      },
      borderRadius: {
        "border-radius-sm": "var(--border-radius-sm)",
        "border-radius-base": "var(--border-radius-base)",
        "border-radius-lg": "var(--border-radius-lg)",
      },
      backdropBlur: {
        xs: "2px",
      },
      zIndex: {
        2: "2",
        200: "200",
        9999: "9999",
      },
      transform: {
        "translate-z-0": "translateZ(0)",
      },
    },
  },
  plugins: [],
};
